### ISSUE TITLE
reload necessary to show updated taxonomy

### ISSUE THREAD

**Issue by joel-st** [felixarntz/attachment-taxonomies#19]
Hey Felix,

First thank you for the awesome plugin! 
I've noticed, that if I choose a new taxonomy in the overlay of an attachment, it is necessary to reload the "media-library" to see the new chosen taxonomy, if I reopen the attachment overlay. 

Thank you for your help and have a nice day!
Joel

**Comment by felixarntz** [comment]
I realize this comes extremely late 😆  However, I recently decided to finally pick up maintenance of this plugin again, and I just fixed this bug in https://github.com/felixarntz/attachment-taxonomies/commit/d410edd47db1e4bb8c5d26dbfe9e6ac2420f3f08 (accidentally referenced the wrong issue in the commit message 🤦).

So this should be fixed with the upcoming 1.2.0 release.
